### ISSUE TITLE
0.8.0.M1 Tracker

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-netty#355]
- [x] :exclamation: Switch 0.8 to master and branch out 0.7.x
    #322 
- [x] :exclamation: 0.8 Public API refactor
    #254 
- [x] Prepend channel ID in all possible logging
    #33
- [x] 0.8.x Package change/Group ID change
    #357 
- [x] Centralize system properties into one constant top level class
    #358 #372 
- [x] UdpServer/UdpClient new API 
    #211 
- [x] TcpServer/TcpClient new API 
    #214 
- [x] HttpServer new API 
    #226 #172
- [x] Remove HttpClientRequest.failOnClientError/failOnServerError
    #93 #118 #182
- [x] Allow setting chunkedTransfer per HttpClient
    #94 #261 
- [x] Allow setting followRedirect per HttpClient
    #235 #260 
- [x] Add support for configuring the HttpRequestDecoder when creating an HttpServer
    #150 #256 
- [x] Support X-Forwarded-* headers 
    #220 #249 #373 
- [x] Replace usage of java.net.URI with UriEndpoint in MonoHttpClientResponse
    #195 #228 
- [x] Introduce properties for enabling ssl debugging
    #227 #262 
- [x] Configure the channel auto read to true for HttpToH2Operations
    #401 
- [x] Add explicit bind exception  enhancement
    #368 #396 #398 
- [x] Consider protocol information when applying the default security configuration
    #384 #394 
- [x] Configure timeout options on HttpClient with new API question
    #390 
- [x] Throw IAE when neither SslContextBuilder nor SslContext is specified
    #387 #389
- [x] Do not create default SSL client provider when creating a server 
    #376 #386 
- [x] Do not create TCP ServerBootstrap in a static block
    #382 #385  
- [x] Remove TcpServer/HttpServer API for using ssl with self singed certificate
    #370 #383 
- [x] fix ssl configuration issue for tcp and http clients
    #369
